version: '3'
services: 
  app:
    container_name: liquid-world-api
    restart: always
    build: .
    ports:
      - '80:3000'
    links: 
      - mongo
    environment: 
      - lwa_jwtSecretKey=12345
      - lwa_db=mongodb://mongo:27017/LWApi
      - db_test=mongodb://mongo:27017/LWApi_test
      - PORT=3000
  mongo: 
    container_name: mongo_db
    volumes: 
      - ~/mongo/data:/data/db
    image: mongo
    ports: 
      - '27017:27017'
