version: '3'
services: 
  app:
    container_name: liquid-world-api
    restart: always
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - '80:3030'
    environment: 
      - PORT=3030
      - db=mongodb://mongo:27017/LWA_db
      - db_tst=mongodb://mongo:27017/LWA_db_tst
      - lwa_jwtSecretKey=1234567890
    links: 
      - mongo
  mongo: 
    container_name: mongo
    image: mongo
    volumes:
      - ~/mongo/data:/data/db
    ports: 
      - '27017:27017'
